### ISSUE TITLE
Build wheels for python 3.11 and 3.12

### ISSUE THREAD

**Issue by jplumail** [fraenkel-lab/pcst_fast#12]
New python users often install the last python version, which is now python 3.12 (https://devguide.python.org/versions/).

**Comment by adrien-berchet** [comment]
Hi there,
I would also need these wheels, @alexlenail could you build and push them please? Or if you wish I can build them for you and post them here.

**Comment by alexlenail** [comment]
I'd love to see a PR for this.

**Comment by adrien-berchet** [comment]
Well, there is not much new in the code but I updated the CI (#14) so we can merge it and create a new release to push to Pypi.

**Comment by adrien-berchet** [comment]
https://pypi.org/project/pcst-fast/1.0.10/ is up and contains wheels for `3.8 <= Python <= 3.12`. Thanks @alexlenail for the release!

**Comment by alexlenail** [comment]
Thanks for the implementation -- hope the package serves you!

**Comment by adrien-berchet** [comment]
Oh yes it does! :)
