### ISSUE TITLE
pypi setup

### ISSUE THREAD

**Issue by ludwigschmidt** [fraenkel-lab/pcst_fast#3]
Is the pypi package currently supposed to work on Mac? When I try to install pcst_fast in a fresh virtualenv on my Mac I get the following error:

http://pastebin.com/UNJzG9tU

**Comment by alexlenail** [comment]
Okay. I managed to install this with `setup.py` locally, so then just pushed to pypi and didn't check. Working on this now

**Comment by alexlenail** [comment]
https://github.com/pybind/python_example/issues/16 seems to be related

**Comment by alexlenail** [comment]
@ludwigschmidt would you try now?

**Comment by ludwigschmidt** [comment]
Did setup.py change? It looks like the only recent change was in the version number:

https://github.com/fraenkel-lab/pcst_fast/commits/master/setup.py

The version from March 22nd didn't work for me. Is there a push missing?

**Comment by alexlenail** [comment]
I didn't change the code per se, but uploaded a wheel instead. Would you mind trying?

**Comment by ludwigschmidt** [comment]
I now get the following error:

https://pastebin.com/Ck9kXNuR

Does `pip install pcst_fast` work on your machine?

**Comment by alexlenail** [comment]
Yes, it works on my machine, but I think wheels are platform dependent, frustratingly.

**Comment by alexlenail** [comment]
@ludwigschmidt 

```
~/Documents/OmicsIntegrator2(master) » pip install --no-cache-dir pcst_fast
Collecting pcst_fast
  Downloading pcst_fast-1.0.2-cp36-cp36m-macosx_10_12_x86_64.whl (66kB)
    100% |████████████████████████████████| 71kB 4.6MB/s
Collecting pybind11>=1.7 (from pcst_fast)
  Downloading pybind11-2.1.0-py2.py3-none-any.whl (109kB)
    100% |████████████████████████████████| 112kB 4.4MB/s
Installing collected packages: pybind11, pcst-fast
Successfully installed pcst-fast-1.0.2 pybind11-2.1.0
------------------------------------------------------------
~/Documents/OmicsIntegrator2(master) » python
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcst_fast
>>> pcst_fast.pcst_fast()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pcst_fast(): incompatible function arguments. The following argument types are supported:
    1. (arg0: numpy.ndarray[int64], arg1: numpy.ndarray[float64], arg2: numpy.ndarray[float64], arg3: int, arg4: int, arg5: str, arg6: int) -> Tuple[numpy.ndarray[int32], numpy.ndarray[int32]]

Invoked with:
>>>
```

**Comment by alexlenail** [comment]
All the wheels should be there now (except for windows). Would you try again?

**Comment by ludwigschmidt** [comment]
Installation works now. Cool!

Two questions before we close this issue:

- I assume we should put the unit tests back into the Travis file?

- How does the Travis script know which commits to push to the pypi directory?

**Comment by alexlenail** [comment]
- There's another issue for the tests, but I agree we should add them. 
- You have to tag the commit. https://git-scm.com/book/en/v2/Git-Basics-Tagging 
- The main reason we can't close this issue is because if you don't have linux/macOS python 2.7 - 3.6 this package is uninstallable. Need to add windows and that "fallback option" we talked about.

**Comment by alexlenail** [comment]
I think we can close this
