### ISSUE TITLE
Possible speedups by unrooting PCST

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/pcst_fast#7]
I've noticed that unrooted PCST runs (in some cases much) faster than rooted PCST. 

In our use case, we solve the PCSF problem by rooting a dummy node with prize 0. An alternative (though slightly dirty) way of rooting a dummy node would be to assign a large prize to it. I've seen speedups 2-4x faster by doing this.

**Comment by alexlenail** [comment]
@ludwigschmidt Would you describe this behavior as expected?

**Comment by iamjli** [comment]
Note that the dummy node is typically very high degree.

**Comment by ludwigschmidt** [comment]
Yes, depending on the graph, 2 - 4x faster sounds plausible.
