### ISSUE TITLE
Support for Python 3.8 and 3.9

### ISSUE THREAD

**Issue by SergeBouchut** [fraenkel-lab/pcst_fast#8]
Hello,

Do you plan to provide support for Python 3.8 and 3.9?

Trying to install it on Debian Buster returns error below.

```bash
docker run -it python:3.9-buster sh
pip install pcst-fast
# ERROR: Could not find a version that satisfies the requirement pcst-fast
# ERROR: No matching distribution found for pcst-fast
```

I am not qualified in C++ or Python bindings, but let me know if I can help.

Thank you for your work!

**Comment by adrien-berchet** [comment]
Anything about this @ludwigschmidt , @fhk , @joerick , @alexlenail ? Would you need help to do it?

**Comment by fhk** [comment]
my understanding is that there isn't anything to stop it working, just need to build and ship to pypi...

But not sure if that's on the cards as I'm not a maintainer.

**Comment by alexlenail** [comment]
Best person to take this on would be @YogiOnBioinformatics I believe. Lots has changed since I set up CI/CD for this repo. Probably it makes sense to use github actions now...

**Comment by adrien-berchet** [comment]
> my understanding is that there isn't anything to stop it working, just need to build and ship to pypi...

Yeah I think that's all we need indeed.

**Comment by ludwigschmidt** [comment]
If someone has time to volunteer for updating the package, that would be great.

**Comment by adrien-berchet** [comment]
I submited #9  to migrate the CI to GH Actions and to automatically push the new releases to Pypi.

**Comment by ludwigschmidt** [comment]
Thank you! It turns out I can't merge pull requests in this repo :-)

@alexlenail, could you merge the PR (and update the Pypi token as Adrien mentioned)? Thanks!
